env:
  browser: true
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2020
rules:
  indent:
    - 2
    - 4
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
