---
version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "$HOME/.webgme/data:/data/db"

  server:
    image: symbench/electric-circuits:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/electric_circuits
      - DEPLOYMENT_PUBLIC_KEY=/token_keys/public_key
      - DEPLOYMENT_PRIVATE_KEY=/token_keys/private_key
      - NODE_ENV=production
      - DEPLOYMENT_BLOB_DIR=/data/blob
    ports:
      - "8888:8888"
    volumes:
      - "$HOME/.webgme/blob:/data/blob"
      - "${TOKEN_KEYS_DIR}:/token_keys"

    depends_on:
      - mongo
