---
version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "$HOME/.webgme/data:/data/db"

  server:
    image: symbench/electric-circuits:latest
    environment:
      - MONGO_URI=mongodb://mongo:27017/electric_circuits
      - NODE_ENV=default
      - DEPLOYMENT_BLOB_DIR=/data/blob
    ports:
      - "8888:8888"
      - "5555:5555"
    volumes:
      - "$HOME/.webgme/blob:/data/blob"

    entrypoint: [npm, start]

    depends_on:
      - mongo
