#!/usr/bin/env bash
DEPLOYMENT_DIR="$(realpath "$(dirname "$0")")"
export DEPLOYMENT_DIR

. ~/.nvm/nvm.sh
docker-compose -p webgme pull server
docker-compose -p webgme stop server
docker-compose -p webgme rm server
docker-compose -p deepforge up -d server

