#!/usr/bin/env bash
DEPLOYMENT_DIR="$(realpath "$(dirname "$0")")"
export DEPLOYMENT_DIR

. ~/.nvm/nvm.sh
docker-compose -p webgme pull server
docker-compose -p webgme stop server
docker-compose -p webgme rm -f server
docker-compose -p webgme up -d server
docker image prune -f
