name: Run Tests and Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['10', '12']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1

      - name: Create Test Environment
        run: conda env create --file environment.yml

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Install Dependencies
        run: npm install --save-dev

      - name: Run Tests
        run: |
          source activate electric-circuits
          npm test

  dockerAndDeploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Publish to docker hub (symbench/electric-circuits:latest)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: symbench/electric-circuits
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: docker-fix

      - name: Deploy (webgme.symbench.org)
        uses: appleboy/ssh-action@master
        if: github.event_name == 'push'
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd webgme-deployment && rm -rf electric-circuits && git clone https://github\
            .com/symbench/electric-circuits.git && cd electric-circuits\
            && chmod +x .deployment/deploy-webgme && ./.deployment/deploy-webgme
